name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: The_First
        run: echo Hello

  test2:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: The_Second
        run: echo ByeBye
        