name: Canary Deployment

on:
  workflow_call:

jobs:
  create_vm_up_compose:
    runs-on: ubuntu-22.04
    env:
      ResourceGroupName: "micsi24sortitoutseul"
      ResourceGroupLocation: "francecentral"

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE }}

      - name: Azure CLI Create Resource Group
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"
    
      - name: Azure ARM Deploy
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json
          parameters: adminUsername=${{ secrets.AZURE_LOGIN }} adminPasswordOrKeys=${{ secrets.AZURE_PW }} vmName="Canary" vmSize="Standard_B2s"

      - name: Get public IP
        if: success()
        uses: azure/CLI@v2
        with:
          inlineScript: |
            VM_IP=$(az vm show -d -g ${{ env.ResourceGroupName }} -n Canary --query publicIps -o tsv)
            echo "AZURE_VM_IP=${VM_IP}" >> $GITHUB_ENV

      - name: Install Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.AZURE_VM_IP }}
          port: 22
          username: ${{ secrets.AZURE_LOGIN }}
          password: ${{ secrets.AZURE_PW }}
          script: |
            curl -o install_docker.sh https://raw.githubusercontent.com/azure-custom-cli/scripts/main/install_docker_ubuntu.sh
            chmod +x install_docker.sh
            bash ./install_docker.sh

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Compose File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.AZURE_VM_IP }}
          port: 22
          username: ${{ secrets.AZURE_LOGIN }}
          password: ${{ secrets.AZURE_PW }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.AZURE_LOGIN }}/"

      - name: Start Compose File
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.AZURE_VM_IP }}
          port: 22
          username: ${{ secrets.AZURE_LOGIN }}
          password: ${{ secrets.AZURE_PW }}
          script: |
            cd /home/${{ secrets.AZURE_LOGIN }}/
            sudo docker pull ghcr.io/hugoreichard/back-ausecours:latest
            sudo docker-compose up -d
