name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: The_First
        run: echo Hello

  test2:
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
      - name: The_Second
        run: echo ByeBye
        
  Biderie:
    needs: [Test2]
    uses: ./.github/workflows/ghcr.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      
  truczer:
    needs: [Biderie]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit

  JeVeuxMourir:
    needs: [truczer]
    uses: ./.github/workflows/canary.yaml
    secrets: inherit